version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fabric-network:
    build:
      context: ./fabric/network
    ports:
      - "7050:7050"
      - "7051:7051"
      - "9051:9051"
    volumes:
      - ./fabric/network/organizations:/opt/fabric/organizations
      - ./fabric/network/channel-artifacts:/opt/fabric/channel-artifacts

  ethereum-node:
    image: ethereum/client-go
    ports:
      - "8545:8545"
      - "30303:30303"
    command: --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,personal,miner" --http.corsdomain "*" --dev

  backend:
    build:
      context: ./fabric/application
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - fabric-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sustainablefashionchain
      - FABRIC_NETWORK_URL=fabric-network:7051

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mongodb_data: